name: "Baseline_Resources"
on:
  workflow_dispatch:
  pull_request: 
    paths-ignore: 
      - '*.md'    
  push:
      branches:
        - deployments  
permissions: write-all  # To update and ensure least priviledge is granted.
  # contents: write
  # issues: write    
jobs:
  Terraform_Plan:
    strategy:
      max-parallel: 1
      matrix:
        environment: [sbx-plan, uat-plan, prd-plan]

    uses: ./.github/workflows/TF_Plan.yml
    with:
      environment: ${{ matrix.environment }}
      path: .          
      tf_version: latest               
    secrets:
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}  

  Terraform_Apply:
    needs: Terraform_Plan
    strategy:
      max-parallel: 1
      matrix:
        environment: [sbx-apply, uat-apply, prd-apply]

    uses: ./.github/workflows/TF_Apply.yml
    with:
      environment: ${{ matrix.environment }}
      path: .          
      tf_version: latest            
    secrets:
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
   
