name: "Baseline_Resources"
on:
  workflow_dispatch: #Allows you to run this workflow manually from the Actions tab
  pull_request:
    branches:
      - main   
  push:
      branches:
        - main         

jobs:
  Terraform_Plan:
    uses: AzureTerraform-AC/Baseline/.github/workflows/TF_Plan.yml@dynamic-file
    with:
      path: ./           
      tf_version: latest 
      tf_vars_file: ./env/dev_baseline.tfvars            
      # az_resource_group: ${{ steps.environment.outputs.AZ_RESOURCE_GROUP }}    
      # az_storage_acc: ${{ steps.environment.outputs.AZ_STORAGE_ACC }}  
      # az_container_name: ${{ steps.environment.outputs.AZ_CONTAINER_NAME }}
      # tf_key: ${{ steps.environment.outputs.TF_KEY }}
    #   enable_TFSEC: true                 ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)
    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}             ## ARM Tenant ID

  Terraform_Apply:
    needs: Terraform_Plan
    uses: AzureTerraform-AC/Baseline/.github/workflows/TF_Apply.yml@dynamic-file
    with:
      path: ./           
      tf_version: latest 
      tf_vars_file: ./env/dev_baseline.tfvars            
      # az_resource_group: ${{ steps.environment.outputs.AZ_RESOURCE_GROUP }}    
      # az_storage_acc: ${{ steps.environment.outputs.AZ_STORAGE_ACC }}  
      # az_container_name: ${{ steps.environment.outputs.AZ_CONTAINER_NAME }}
      # tf_key: ${{ steps.environment.outputs.TF_KEY }}  
    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}             ## ARM Tenant ID            
