name: "Run Checks"

on: 
    workflow_call:

jobs: 
  running-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2        

        # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
    # Install Checkov
      - name: Install Checkov
        id: checkov
        run: pip3 install checkov
      - name: Show Checkov Version
        run: checkov -v

      - name: Run Checkov
        run: checkov -d . -o sarif -s --framework terraform --skip-check CKV_AZURE_59,CKV_AZURE_40,CKV_AZURE_53,CKV_AZURE_37,CKV_AZURE_41,CKV_AZURE_1            

      - name: Upload Checkov Artifact
        uses: actions/upload-artifact@v4
        with:
            name: checkov-results
            path: ./results.sarif     

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true

      - name: Check linting of Terraform files
        uses: devops-infra/action-tflint@v0.3
        with:
          tflint_config: modules/.tflint.hcl

      # # TFLint Checks (To fix the issue with TF version [Bug?])  
      # - uses: actions/checkout@v4  
      # - uses: actions/cache@v4           # TFLint - Terraform Check 
      #   name: Cache plugin dir
      #   with:
      #       path: ~/.tflint.d/plugins
      #       key: tflint-${{ hashFiles('.tflint.hcl') }}
      # - uses: terraform-linters/setup-tflint@v4
      #   name: Setup TFLint
      #   with:
      #     tflint_version: latest
      # - name: Show version                # Print TFLint version
      #   run: tflint --version
      # - name: Init TFLint                 # Install plugins
      #   run: tflint --init
      # - name: Run TFLint & export result # Run tflint command in each directory recursively # use --force if you want to continue with workflow although errors are there
      #   run: |
      #       tflint -f compact --recursive
      #       touch tflint-results.json
      #       tflint -f json --recursive --force >> tflint-results.json
      # - name: Upload Tflint Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #       name: tflint-results
      #       path: ./tflint-results.json   



