name: Export Environment Variables
'on':
    workflow_dispatch: null
    pull_request:
      branches:
        - main
    push:
      branches:
        - main

jobs:
  export_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .env variables
        run: |
          source ./.env
          echo "AZ_RESOURCE_GROUP=${{ env.AZ_RESOURCE_GROUP }}" >> $GITHUB_OUTPUT
          echo "AZ_STORAGE_ACC=${{ env.AZ_STORAGE_ACC }}" >> $GITHUB_OUTPUT
          echo "AZ_CONTAINER_NAME=${{ env.AZ_CONTAINER_NAME }}" >> $GITHUB_OUTPUT
          echo "TF_KEY=${{ env.TF_KEY }}" >> $GITHUB_OUTPUT

      - name: Echo environment variables
        run: |
          echo "AZ_RESOURCE_GROUP=${AZ_RESOURCE_GROUP}"
          echo "AZ_STORAGE_ACC=${AZ_STORAGE_ACC}"
          echo "AZ_CONTAINER_NAME=${AZ_CONTAINER_NAME}"
          echo "TF_KEY=${TF_KEY}"

